### Intrinsic NumPy array creation using NumPy's Methods

In [2]:
import numpy as np

In [3]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
np.arange(10, 23) - 10+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
len(np.arange(10, 23))

13

In [6]:
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [7]:
np.arange(10, 23).size

13

In [8]:
np.arange(10,23,5)

array([10, 15, 20])

In [12]:
my_linspace = np.linspace(5, 15, 9, retstep = True)

In [14]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [16]:
my_linspace[1]

1.25

### zeros()

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Ones()

In [20]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.zeros(11,dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)